// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HX0pVhDWCSRWzBqcst2fqBSHYjUE3jY',
    appId: '1:1077333061578:web:5fe222b7b1229a34206933',
    messagingSenderId: '1077333061578',
    projectId: 'car-rental-app-f8b9c',
    authDomain: 'car-rental-app-f8b9c.firebaseapp.com',
    storageBucket: 'car-rental-app-f8b9c.firebasestorage.app',
    measurementId: 'G-9X03TP49NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAK9UZhNEaqmVL-pex6P8Z5Mp2Kl2wCgo',
    appId: '1:1077333061578:android:733ed791f027a11f206933',
    messagingSenderId: '1077333061578',
    projectId: 'car-rental-app-f8b9c',
    storageBucket: 'car-rental-app-f8b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmW5PxvgZId88WisSr603tNeYHn7xcXnM',
    appId: '1:1077333061578:ios:0142be037684fd70206933',
    messagingSenderId: '1077333061578',
    projectId: 'car-rental-app-f8b9c',
    storageBucket: 'car-rental-app-f8b9c.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );
}
